In [2]:
import xclim
import numpy as np
import xarray as xr

In [3]:
lat = np.random.uniform(low=-90, high=90, size=(4,5))
lon = np.random.uniform(low=-180, high=180, size=(4,5))

In [4]:
test_arr = np.random.randint(1, 10, size=(4,5))
test_arr, lat , lon = np.around([test_arr, lat, lon], decimals=2)
test_da = xr.DataArray(data=test_arr,
                  coords={"lat": (["x","y"], lat),
                          "lon": (["x","y"], lon)},
                  dims=["x","y"])
test_da.attrs['units'] = 'mm/hour'
test_da

<xarray.DataArray (x: 4, y: 5)>
array([[6., 3., 5., 1., 5.],
       [4., 7., 3., 3., 3.],
       [4., 1., 1., 9., 4.],
       [3., 9., 8., 4., 4.]])
Coordinates:
    lat      (x, y) float64 72.07 -11.82 10.54 -3.7 ... -69.46 -10.83 -3.63
    lon      (x, y) float64 -141.3 -33.0 -47.35 35.22 ... -46.81 -134.3 65.67
Dimensions without coordinates: x, y
Attributes:
    units:    mm/hour

In [6]:
delta_arr = np.random.randint(2, 4, size=(4,5))
delta_arr, lat , lon = np.around([delta_arr, lat, lon], decimals=2)
delta_da = xr.DataArray(data=delta_arr,
                  coords={"lat": (["x","y"], lat),
                          "lon": (["x","y"], lon)},
                  dims=["x","y"])
delta_da.attrs['units'] = 'delta_degreeC'
delta_da

<xarray.DataArray (x: 4, y: 5)>
array([[3., 3., 3., 3., 2.],
       [3., 2., 3., 3., 2.],
       [3., 2., 2., 2., 3.],
       [3., 3., 2., 2., 3.]])
Coordinates:
    lat      (x, y) float64 72.07 -11.82 10.54 -3.7 ... -69.46 -10.83 -3.63
    lon      (x, y) float64 -141.3 -33.0 -47.35 35.22 ... -46.81 -134.3 65.67
Dimensions without coordinates: x, y
Attributes:
    units:    delta_degreeC

In [7]:
otpt = xclim.indices.clausius_clapeyron_scaled_precipitation(delta_da, test_da)
otpt

<xarray.DataArray (x: 4, y: 5)>
array([[ 7.350258,  3.675129,  6.125215,  1.225043,  5.7245  ],
       [ 4.900172,  8.0143  ,  3.675129,  3.675129,  3.4347  ],
       [ 4.900172,  1.1449  ,  1.1449  , 10.3041  ,  4.900172],
       [ 3.675129, 11.025387,  9.1592  ,  4.5796  ,  4.900172]])
Coordinates:
    lat      (x, y) float64 72.07 -11.82 10.54 -3.7 ... -69.46 -10.83 -3.63
    lon      (x, y) float64 -141.3 -33.0 -47.35 35.22 ... -46.81 -134.3 65.67
Dimensions without coordinates: x, y
Attributes:
    units:    mm hr-1

In [8]:
basic_otpt = test_da * (1.07 ** delta_da)
basic_otpt

<xarray.DataArray (x: 4, y: 5)>
array([[ 7.350258,  3.675129,  6.125215,  1.225043,  5.7245  ],
       [ 4.900172,  8.0143  ,  3.675129,  3.675129,  3.4347  ],
       [ 4.900172,  1.1449  ,  1.1449  , 10.3041  ,  4.900172],
       [ 3.675129, 11.025387,  9.1592  ,  4.5796  ,  4.900172]])
Coordinates:
    lat      (x, y) float64 72.07 -11.82 10.54 -3.7 ... -69.46 -10.83 -3.63
    lon      (x, y) float64 -141.3 -33.0 -47.35 35.22 ... -46.81 -134.3 65.67
Dimensions without coordinates: x, y

In [9]:
otpt - basic_otpt

<xarray.DataArray (x: 4, y: 5)>
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])
Coordinates:
    lat      (x, y) float64 72.07 -11.82 10.54 -3.7 ... -69.46 -10.83 -3.63
    lon      (x, y) float64 -141.3 -33.0 -47.35 35.22 ... -46.81 -134.3 65.67
Dimensions without coordinates: x, y